[package]
name = "accelerate"
version = "2.0.0"
description = "Accelerate back and forth through time for your database or other in-place systems"
homepage = "https://github.com/calebmer/accelerate"
repository = "calebmer/accelerate"
readme = "README.md"
license = "MIT"
keywords = ["database",
            "migrate",
            "sql"]
authors = ["Caleb Meredith <calebmeredith8@gmail.com>",
           "Victor M. Suarez <svmnotn@gmail.com>"]
[dependencies]
regex = "0.1.41"
postgres = "0.10"
